# Generated by Django 4.2.4 on 2023-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Id', models.EmailField(max_length=254, unique=True)),
                ('Phone_No', models.CharField(max_length=256)),
                ('Full_Name', models.CharField(max_length=256)),
                ('Password', models.CharField(max_length=256)),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
