# Generated by Django 4.2.4 on 2023-08-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.EmailField(max_length=254, unique=True)),
                ('hospital_id', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=100)),
                ('Slot', models.CharField(max_length=100)),
                ('Date1', models.CharField(max_length=100)),
                ('Date2', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('scheduled', models.CharField(max_length=255)),
            ],
        ),
    ]
