# Generated by Django 4.2.4 on 2023-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.EmailField(max_length=254, unique=True)),
                ('history', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='Date1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='Date2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='Doctor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='Hospital',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='Slot',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='doctor_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='hospital_id',
            field=models.CharField(max_length=255),
        ),
    ]
